"""
Pre-bite and post-bite document generator.

Produces two SEPARATE, fully editable .docx files (a Word document each):
  * pre-bite  — what participants do BEFORE the session (prep / reading / setup)
  * post-bite — what they do AFTER (reflection / assignment / further reading)

Falls back to Markdown if python-docx is unavailable, so the pipeline never
hard-fails on a missing optional dependency.
"""

from __future__ import annotations

from pathlib import Path
from typing import Tuple

from .config import Color
from .schema import Bite, Training

try:
    from docx import Document
    from docx.shared import Pt, RGBColor, Inches
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    _HAS_DOCX = True
except Exception:  # pragma: no cover
    _HAS_DOCX = False


def _rgb(hexv: str):
    return RGBColor(int(hexv[0:2], 16), int(hexv[2:4], 16), int(hexv[4:6], 16))


def _docx_bite(tr: Training, bite: Bite, kind: str, path: Path) -> str:
    doc = Document()
    style = doc.styles["Normal"]
    style.font.name = "Calibri"
    style.font.size = Pt(11)

    kicker = doc.add_paragraph()
    kr = kicker.add_run(f"MAVERX · {kind.upper()}")
    kr.bold = True
    kr.font.size = Pt(10)
    kr.font.color.rgb = _rgb(Color.ORANGE)

    h = doc.add_heading(bite.title, level=0)
    for run in h.runs:
        run.font.color.rgb = _rgb(Color.INDIGO)

    meta = doc.add_paragraph()
    mr = meta.add_run(f"Training: {tr.title}    ·    Audience: {tr.audience}"
                      f"    ·    Level: {tr.level}")
    mr.italic = True
    mr.font.size = Pt(9)
    mr.font.color.rgb = _rgb(Color.BLACK)

    if bite.intro:
        doc.add_paragraph(bite.intro)

    for section, items in bite.sections.items():
        items = [i for i in items if str(i).strip()]
        if not items:
            continue
        sh = doc.add_heading(section, level=1)
        for run in sh.runs:
            run.font.color.rgb = _rgb(Color.PURPLE)
        for it in items:
            doc.add_paragraph(str(it), style="List Bullet")

    foot = doc.add_paragraph()
    fr = foot.add_run("Generated by the Maverx AI Training Builder · maverx.nl")
    fr.font.size = Pt(8)
    fr.font.color.rgb = _rgb(Color.BLACK)

    doc.save(str(path))
    return str(path)


def _md_bite(tr: Training, bite: Bite, kind: str, path: Path) -> str:
    lines = [f"<!-- MAVERX · {kind.upper()} -->", f"# {bite.title}", "",
             f"*Training: {tr.title} · Audience: {tr.audience} · Level: {tr.level}*", ""]
    if bite.intro:
        lines += [bite.intro, ""]
    for section, items in bite.sections.items():
        items = [i for i in items if str(i).strip()]
        if not items:
            continue
        lines.append(f"## {section}")
        lines += [f"- {it}" for it in items]
        lines.append("")
    path = path.with_suffix(".md")
    path.write_text("\n".join(lines), encoding="utf-8")
    return str(path)


def build_bites(tr: Training, out_dir: Path, slug: str) -> Tuple[str, str]:
    out_dir = Path(out_dir)
    pre_path = out_dir / f"{slug}_pre-bite.docx"
    post_path = out_dir / f"{slug}_post-bite.docx"
    if _HAS_DOCX:
        return (_docx_bite(tr, tr.prebite, "Pre-bite", pre_path),
                _docx_bite(tr, tr.postbite, "Post-bite", post_path))
    return (_md_bite(tr, tr.prebite, "Pre-bite", pre_path),
            _md_bite(tr, tr.postbite, "Post-bite", post_path))
